name       : python-pyocr
version    : 0.7.1
release    : 6
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/pyocr/-/archive/0.7.1/pyocr-0.7.1.tar.bz2 : 5fecad98d43dda2a629eff639407519445eec3387d9547eb45923ea8ba4bb0df
license    : GPL-3.0-or-later
component  : programming.python
summary    : A Python wrapper for Tesseract and Cuneiform
description: |
    PyOCR is an optical character recognition (OCR) tool wrapper for python. That is, it helps using OCR tools from a Python program.
networking : yes
builddeps  :
    - pkgconfig(tesseract)
rundeps    :
    - python-pillow
    - tesseract
build      : |
    %python3_setup
install    : |
    %python3_install
