name       : python-pyocr
version    : 0.4.6
release    : 3
source     :
    - https://github.com/jflesch/pyocr/archive/0.4.6.tar.gz : 1b8b8eac73de03750857edfd58cd8b4b73f025493bd08300121a6c26591ed78a
license    : GPL-3.0
component  : programming.python
summary    : A Python wrapper for Tesseract and Cuneiform
description: |
    PyOCR is an optical character recognition (OCR) tool wrapper for python. That is, it helps
    using OCR tools from a Python program.
builddeps  :
    - pkgconfig(tesseract)
    - python-setuptools
rundeps    :
    - python-pillow
    - tesseract
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
