name       : python-pyocr
version    : 0.8.2
release    : 11
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/pyocr/-/archive/0.8.2/pyocr-0.8.2.tar.gz : 36c99c35c1ef5f92e56c6046700bf760415bed8edd17b018b1978a9b0504b701
homepage   : https://gitlab.gnome.org/World/OpenPaperwork/pyocr
license    : GPL-3.0-or-later
component  : programming.python
summary    : A Python wrapper for Tesseract and Cuneiform
description: |
    PyOCR is an optical character recognition (OCR) tool wrapper for python. That is, it helps using OCR tools from a Python program.
builddeps  :
    - pkgconfig(tesseract)
    - python-setuptools-scm-git-archive
rundeps    :
    - python-pillow
    - tesseract
build      : |
    %python3_setup
install    : |
    %python3_install
