name       : python-pyocr
version    : 0.8.0
release    : 7
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/pyocr/-/archive/0.8/pyocr-0.8.tar.gz : 8a0ee91ce9b4f5b8b9e540c1400a0d4ee7624d4c8ad056573ea81aa411748d29
license    : GPL-3.0-or-later
component  : programming.python
summary    : A Python wrapper for Tesseract and Cuneiform
description: |
    PyOCR is an optical character recognition (OCR) tool wrapper for python. That is, it helps using OCR tools from a Python program.
networking : yes
builddeps  :
    - pkgconfig(tesseract)
rundeps    :
    - python-pillow
    - tesseract
build      : |
    %python3_setup
install    : |
    %python3_install
