name       : python-pyocr
version    : 0.8.1
release    : 9
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/pyocr/-/archive/0.8.1/pyocr-0.8.1.tar.gz : 649808c9fd30c095216917fb70caa99298af11d2606f4437e04a7f8857057a0c
homepage   : https://gitlab.gnome.org/World/OpenPaperwork/pyocr
license    : GPL-3.0-or-later
component  : programming.python
summary    : A Python wrapper for Tesseract and Cuneiform
description: |
    PyOCR is an optical character recognition (OCR) tool wrapper for python. That is, it helps using OCR tools from a Python program.
builddeps  :
    - pkgconfig(tesseract)
    - python-setuptools-scm-git-archive
rundeps    :
    - python-pillow
    - tesseract
build      : |
    %python3_setup
install    : |
    %python3_install
